# Generated by Django 4.2.2 on 2024-02-21 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="shared_users",
            field=models.ManyToManyField(
                related_name="shared_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
