# Generated by Django 4.2.2 on 2024-02-22 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_noteversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteversion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
